export const INITIAL_STATE = 'UI-INITIAL_STATE'
export const SET_FIREBASE_READY = 'UI-SET_FIREBASE_READY'
export const SET_VIEWPORT = 'UI-SET_VIEWPORT'
export const SET_SHOW_LOGIN = 'UI-SET_SHOW_LOGIN'
